os:
- linux
# - osx
before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi'
language: node_js
node_js:
# - node
# - '11'
# - '10'
# - '8'
# - '6'
- lts/*
install:
- npm install
- npm run global
script:
- npm run test
- npm run coverage
before_deploy:
- npm run rules
deploy:
- provider: npm
  email: "perez.lamed.vanniekerk@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    commit_message: "release"
    repo: perezLamed/see_it_done
